[app]
address = "0.0.0.0:6000" # Address of the HTTP Server.
server_timeout = "60s" # Server timeout for HTTP requests.
enable_request_logs = true # Whether to log incoming HTTP requests or not.
log = "info" # Use `debug` to enable verbose logging. Can be set to `info` otherwise.

[providers.prod_payment_alerts]
type = "google_chat" # Type of provider. Currently supported value is `google_chat`.
endpoint = "https://chat.googleapis.com/v1/spaces/AAAAWT-YcfE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=zPu_DLzw8fS9HRqwb_AkkAgXXIQAJ4tREEgF_0nCg7I" # Google Chat Webhook URL
max_idle_conns =  50 # Max idle connections in the HTTP Client.
timeout = "30s" # Timeout for making requests to Provider.
template = "static/RPS_EXCEEDED.tmpl" # Path to specify the message template path.
thread_ttl = "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
threaded_replies = false # Whether to send threaded replies or not.
dry_run = false

[providers.qa_payment_alerts]
type = "google_chat" # Type of provider. Currently supported value is `google_chat`.
endpoint = "https://chat.googleapis.com/v1/spaces/AAAANoBANpo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=UTMgJT3SGgOIJRH8vxIN-FBh42VxoSh_qrOvPD8lMvc" # Google Chat Webhook URL
max_idle_conns =  50 # Max idle connections in the HTTP Client.
timeout = "30s" # Timeout for making requests to Provider.
template = "static/RPS_EXCEEDED.tmpl" # Path to specify the message template path.
thread_ttl = "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
threaded_replies = false # Whether to send threaded replies or not.
dry_run = false