apiVersion: apps/v1
kind: Deployment
metadata:
  name: calert
  labels:
    app.kubernetes.io/name: calert
    app.kubernetes.io/instance: release-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: calert
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calert
    spec:
      restartPolicy: Always
      imagePullSecrets:
            - name: dockercred
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        readOnlyRootFilesystem: true
      containers:
        - name: calert
          image: "ghcr.io/mr-karan/calert:v2.0.2"
          imagePullPolicy: Always
          args:
            - "--config=/app/static/config.toml"
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE"]
          ports:
            - containerPort: 6000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/static/
              name: config-dir
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: X-Causation-ID
                  value: kube-health
              path: "/ping"
              port: 6000
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: X-Causation-ID
                  value: kube-health
              path: "/ping"
              port: 6000
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "20m"
              memory: "48Mi"
            requests:
              cpu: "5m"
              memory: "24Mi"
      volumes:
        - name: config-dir
          hostPath:
            path: /path/to/your/local/folder
            type: Directory
      nodeSelector:


