apiVersion: v1
kind: Service
metadata:
  name: "calert-svc"
  namespace: ingress-calert
spec:
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
  selector:
    app.kubernetes.io/name: calert
