apiVersion: apps/v1
kind: Deployment
metadata:
  name: calert
  namespace: prometheus
  labels:
    app: calert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calert
  template:
    metadata:
      labels:
        app: calert
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockercred
      containers:
        - name: calert
          image: "578061096415.dkr.ecr.us-east-1.amazonaws.com/calert:1.0.3"
          imagePullPolicy: Always
          args:
            - "--config=/app/config.toml"
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["NET_BIND_SERVICE"]
          ports:
            - containerPort: 6000
              protocol: TCP
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: X-Causation-ID
                  value: kube-health
              path: "/ping"
              port: 6000
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: X-Causation-ID
                  value: kube-health
              path: "/ping"
              port: 6000
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
            requests:
              cpu: "1000m"
              memory: "1024Mi"
      nodeSelector:
        cluster: prometheus
        kubernetes.io/arch: arm64


